version: 0.2

phases:
  install:
    commands:
      - powershell -NoProfile -ExecutionPolicy Bypass -File build\publish.ps1

artifacts:
  files:
    - '**/*'
  base-directory: dist
  discard-paths: no